// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  'aws_project_region': 'us-west-2',
  'aws_cognito_identity_pool_id': 'us-west-2:4175f777-847f-4177-bceb-9cb5eb2a062b',
  'aws_cognito_region': 'us-west-2',
  'aws_user_pools_id': 'us-west-2_Hx4gI38FX',
  'aws_user_pools_web_client_id': '7vi108k08tufu2o0ck4uvravg9',
  'aws_content_delivery_bucket': 'flyorterfrontendv2-20181221115532-hostingbucket',
  'aws_content_delivery_bucket_region': 'us-west-2',
  'aws_content_delivery_url': 'http://flyorterfrontendv2-20181221115532-hostingbucket.s3-website-us-west-2.amazonaws.com',
};


export default awsmobile;
